providers:
  gmx:
    imap_server: imap.gmx.net
    smtp_server: mail.gmx.net
    imap_port: 993
    smtp_port: 587
  gmail:
    imap_server: imap.gmail.com
    smtp_server: smtp.gmail.com
    imap_port: 993
    smtp_port: 587
  yahoo:
    imap_server: imap.mail.yahoo.com
    smtp_server: smtp.mail.yahoo.com
    imap_port: 993
    smtp_port: 587
  outlook:
    imap_server: outlook.office365.com
    smtp_server: smtp.office365.com
    imap_port: 993
    smtp_port: 587
